### ISSUE TITLE
warning: 'packed' attribute ignored for field of type 'uint8_t [1024]'

### ISSUE THREAD

**Issue by Andy2051** [xreef/SimpleFTPServer#10]
Using on a nodemcu, the arduino IDE is generating the above warning on compiling. Uploaded code works okay and can transfer files using filezilla.

Warning removed by changing FtpServer.h, line 646 from 
`uint8_t  __attribute__((packed, aligned(4))) // need to be aligned to 32bit for Esp8266 SPIClass::transferBytes()`
to
`uint8_t  __attribute__((aligned(4))) // need to be aligned to 32bit for Esp8266 SPIClass::transferBytes()`
Filezilla can still upload files.

**Comment by xreef** [comment]
Thanks @Andy2051,
I'm going to try in deep and release it in the next release.
Bye Renzo
