### ISSUE TITLE
Add a Flag to remove all debug 

### ISSUE THREAD

**Issue by buzzcola3** [xreef/SimpleFTPServer#12]
It would be nice to have a flag that removes all debugging/serial output.

In my project, the serial is wired to a 3d printer

**Comment by xreef** [comment]
Ops... sorry I forgot to comment this line
https://github.com/xreef/SimpleFTPServer/blob/master/FtpServerKey.h#L21

I must redò a new version.

Now comment that line.

bye Renzo

**Comment by buzzcola3** [comment]
Nwm, found it
