### ISSUE TITLE
uint16_t FtpServer::fileSize( FTP_FILE file ) should be uint32_t

### ISSUE THREAD

**Issue by kevin6112** [xreef/SimpleFTPServer#13]
Hi, thanks for the great project.

Using iOS clients FTPManage or FE File Explorer or FTP Rush:
Client aborts for files >32kB. 

I believe this is because client relies on the file size sent in
    683    client.print( F("150 ") ); client.print( long( fileSize( file )) ); client.println( F(" bytes to download") );

However, fileSize is declared as uint16_t
  2111   uint16_t FtpServer::fileSize( FTP_FILE file ) {

Declaring fileSize as uint32_t resolves the issue. I have tested and confirmed this.

This also resolves incorrect file size displayed in
   675    DEBUG_PRINT( F(" Sending ") ); DEBUG_PRINT( parameter ); DEBUG_PRINT( F(" size ") ); DEBUG_PRINTLN( long( fileSize( file ))  );

Thank you

**Comment by xreef** [comment]
Hi Kevin,
Thanks a lot; I'm going to fix this.
This month, the second issue was generated by improperly using a variable (I always try to reduce the memory size).
Thanks again Renzo
