### ISSUE TITLE
LIST shall returns file name but actually full path for STORAGE_SD

### ISSUE THREAD

**Issue by cat-in-136** [xreef/SimpleFTPServer#19]
LIST shall returns file names but actually full path in case of STORAGE_TYPE == STORAGE_SD.

Expected ftp command response text:

```cmd
ftp> cd foo
250 Directory changed to /foo
ftp> ls
227 Entering Passive Mode (xxx,xxx,xxx,xxx,195,89)
150 Accepted data connection to port 50009
-rw-rw-r--	1	esp32	67077	Jan 01 00:00	bar.dat
226 1 matches total
```

Actual ftp command response text:

```cmd
ftp> cd foo
250 Directory changed to /foo
ftp> ls
227 Entering Passive Mode (xxx,xxx,xxx,xxx,195,89)
150 Accepted data connection to port 50009
-rw-rw-r--	1	esp32	67077	Jan 01 00:00	/foo/bar.dat
226 1 matches total
```

**Comment by xreef** [comment]
Thanks, @cat-in-136,
now I'm on holiday, so I can't test in all environments and core versions of your change, but when I return home I integrate your change.
Thanks again Renzo
