### ISSUE TITLE
Does not work on Acess point mode, only Station mode

### ISSUE THREAD

**Issue by Capiten** [xreef/SimpleFTPServer#22]
Hi

I have been using this great library on STA mode, but recently I got a project where there was no wifi available, so I thought I could do it on AP mode (or even AP+STA mode). But it does not work.
Here is what I get on arduino IDE:
`ets Jul 29 2019 12:21:46

rst:0x1 (POWERON_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:1
load:0x3fff0030,len:1344
load:0x40078000,len:13516
load:0x40080400,len:3604
entry 0x400805f0
Set AP named:ESP32
AP IP address: 192.168.4.1
Card Mount Successful.
SD opened!
Listing directory: /
 DIR : System Volume Information
 DIR : Data
 FILE: .dropbox.device SIZE: 56
 FILE: Backup_dongle.txt SIZE: 370
 FILE: settings.txt SIZE: 368
NOT ANONYMOUS
esp32
 Ftp server waiting for connection on port 21
 Client connected!
>>>>>>>>>>>>>>> _callback 0 1 1
CONNECTED
-U-S-E-R- -e-s-p-3-2-
-
Command is: USER
USER: esp32 esp32
-P-A-S-S- -e-s-p-3-2-
-
Command is: PASS
 Authentication Ok. Waiting for commands.
-O-P-T-S- -U-T-F-8- -O-N-
-
Command is: OPTS
200 OK, UTF8 ON
-P-W-D-
-
Command is: PWD
-T-Y-P-E- -I-
-
Command is: TYPE
-P-A-S-V-
-
Command is: PASV
 Connection management set to passive
 Listening at 0.0.0.0:50009
-M-L-S-D-
-
Command is: MLSD
List of file!!`
And what I get on Filezilla:
`Status:	Connecting to 192.168.4.1:21...
Status:	Connection established, waiting for welcome message...
Status:	Plain FTP is insecure. Please switch to FTP over TLS.
Status:	Logged in
Status:	Retrieving directory listing...
Command:	PWD
Response:	257 "/" is your current directory
Command:	TYPE I
Response:	200 TYPE is now 8-bit binary
Command:	PASV
Response:	227 Entering Passive Mode (0,0,0,0,195,89)
Command:	MLSD
Error:	The data connection could not be established: WSAEADDRNOTAVAIL - Cannot assign requested address
Response:	425 No data connection
Error:	Failed to retrieve directory listing`

Finally, I'm using arduino IDE 1.8.19 and esp32 board version 2.0.3.

I'm also attatching an arduino code where >I manage to do it in STA mode and if I comment and discomment STA part and AP part, I should get it to work on AP mode (but doesn't work and produce what I just posted here.
[ESP32_FTP_STA_n_AP.txt](https://github.com/xreef/SimpleFTPServer/files/8966549/ESP32_FTP_STA_n_AP.txt)

Thank you!
Cheers, Luís Pereira.

**Comment by xreef** [comment]
Continue here.
https://www.mischianti.org/forums/topic/esp8266-from-stattion-mode-to-access-point-mode-with-ftpserver-code/
