### ISSUE TITLE
Example Server: Disconnect Event never called

### ISSUE THREAD

**Issue by Joshy-2010** [xreef/SimpleFTPServer#30]
Not a critical bug, but just wanted to report in case it helps anyone:
I used [this](https://www.mischianti.org/2020/02/08/ftp-server-on-esp8266-and-esp32/) example for a simple SPIFFS server based on esp32. Everything works fine, but after disconnecting filezilla 

case FTP_DISCONNECT:
      Serial.println(F("FTP: Disconnected!"));
      break;

is not called. At least I do not see the Serial log message. Strangely, all other messages (connect, file transfer, ...) are pritned correctly.

**Comment by xreef** [comment]
Hi joshy,
I must verify. I don't know if the disconnection is from the client and the server does not detect It.
Bye Renzo

**Comment by xreef** [comment]
Fixed in the next release.
