### ISSUE TITLE
Error modifying files via ftp.

### ISSUE THREAD

**Issue by ForceConstant** [xreef/SimpleFTPServer#4]
So I have this setup in my esp32 sketch, and am able to connect and view/upload files, but am not able to delete or rename files. 

For example I login and see /heart.gif, if I try to delete I get below.  

```
  --> FTP reconnected
Deleting file /heart.gif...
>>>  DELE /heart.gif
<<<  550 /heart.gif not found.

>>>  CWD .
<<<  257 "/" is your current directory
```

**Comment by xreef** [comment]
Hi,
What configuration you use?
Bye Renzo

**Comment by ForceConstant** [comment]
Setup just like the example in  the Readme.  Esp32 programmed with platform io.

**Comment by xreef** [comment]
SPIFFS and wifi as standard?
Bye Renzo

**Comment by ForceConstant** [comment]
Yes

**Comment by xreef** [comment]
Hi ForceConstant,
I try and seems that all work correctly

![image](https://user-images.githubusercontent.com/1850282/142641406-e74749f2-3518-4274-ae64-a2cb11428383.png)

can you give me some other information?

Bye Renzo

**Comment by xreef** [comment]
No answer.
