### ISSUE TITLE
PlatformIO ESP32 compilation error

### ISSUE THREAD

**Issue by DjordjeMandic** [xreef/SimpleFTPServer#43]
I kept getting error that `File` was not defined. Actual `File` is inside `fs` namespace and it was not accessible. This fixed it

```
#ifdef ESP32
	#if ESP_ARDUINO_VERSION_MAJOR >= 2
			#include "FS.h"
			#include "LittleFS.h"
			#define STORAGE_MANAGER LittleFS
			
			using namespace fs;
			
	#else
			#include "LITTLEFS.h"
			#define STORAGE_MANAGER LITTLEFS
	#endif
#else
```

https://github.com/xreef/SimpleFTPServer/blob/9f36a4ad289178cde7a7fa931274d1f08e728643/FtpServer.h#L319-L328

**Comment by xreef** [comment]
Hi DjordjeMandic,
I tested It without any change, and it works properly. Try the example provided.
Bye Renzo
