### ISSUE TITLE
'Sd2Card' does not name a type !!!

### ISSUE THREAD

**Issue by DR-DNK** [xreef/SimpleFTPServer#47]
Hey!!! I am using SEEED SAMD Board v1.8.5 (Seeeduino wio terminal ) and I want to run SimpleFTPServer . I am running the given example code in Arduino IDE . My libraries version for SdFat and SimpleFTPServer are given below .
SdFat v2.2.2 
SimplFTPServer v2.1.6

Below is the example I want to run and that's why I have also included the required library .
https://mischianti.org/2021/07/01/simple-ftp-server-library-now-with-support-for-wio-terminal-and-sd/

These are the libraries I have installed .
Adafruit_ZeroDMA
SdFat
Seeed_Arduino_FreeRTOS
Seeed_Arduino_FS
Seeed_Arduino_mbedtls
Seeed_Arduino_rpcUnified
Seeed_Arduino_rpcWiFi
Seeed_Arduino_SFUD
SimpleFTPServer
SPI

Below is the given example code and the error_log.txt which consist of the error I am encountering . Please help me to run the default example code for SimpleFTPServer in Arduino IDE.

[Wio_terminal_SdFat.zip](https://github.com/xreef/SimpleFTPServer/files/12893797/Wio_terminal_SdFat.zip)
[error_logs.txt](https://github.com/xreef/SimpleFTPServer/files/12893799/error_logs.txt)

**Comment by DR-DNK** [comment]
@xreef 
Can you please provide me some insights on this , that would be of great help??

**Comment by xreef** [comment]
Hi DR-DNK,
I try to build the TFT example, and standard SD library example and It’s work correctly without errors.

Check the FTP key configuration and retry.

Bye Renzo

**Comment by DR-DNK** [comment]
Hey Renzo !!!
My error was solved . I think the problem was when I downloaded the SimpleFTPServer library in Arduino IDE , the below section was not commented in FTPServerKey.h file , while I was using the wio terminal configuration .

// Arduino SAMD
#define DEFAULT_FTP_SERVER_NETWORK_TYPE_SAMD
NETWORK_WiFiNINA
#define DEFAULT_STORAGE_TYPE_SAMD STORAGE_SD

As and when I commented that section and compiled the code , no errors were found .

Thank you Renzo for bearing with me .
