### ISSUE TITLE
ESP32 file system defaults to FAT32?

### ISSUE THREAD

**Issue by MajicDesigns** [xreef/SimpleFTPServer#54]
I tried the ESP8266_ESP_32_LittleFS example and it appears that the file system for ESP32 by default is FAT32. This seems to be confirmed by digging into the header file #define heirarchy maze.

I am missing something here? I would like to specify the file system independent of the ESP32 #define.

**Comment by xreef** [comment]
Hi, 
you can set the LittleFS on this [keyword](https://github.com/xreef/SimpleFTPServer/blob/master/FtpServerKey.h#L63).
Bye Renzo
