### ISSUE TITLE
Problem with Buffer size when compiling (esp32 Dev kit V1)

### ISSUE THREAD

**Issue by Gabryxx** [xreef/SimpleFTPServer#7]
SimpleFTPServer/FtpServer.h:639:30: warning: 'packed' attribute ignored for field of type 'uint8_t [2048]' {aka 'unsigned char [2048]'} [-Wattributes]

**Comment by xreef** [comment]
Hi Gabry,
I know that warning, but don't generate any problems.
Thanks Renzo

**Comment by Gabryxx** [comment]
Ok, ma il buffer viene generato coi valori immessi oppure no?
    Cioè se gli metto 1024 viene generato un buffer 1024 o viene
      ignorato il comando?
    ma mi rispondo da solo : Mi sembra che la velocità di
      trasferimento sia la stessa, per cui non viene considerato
    Se ti interessa sto sviluppando un esempio che usa anche la tua
      libreria e le LVGL con Esp32 e touch screen Ili9488
    qua il link ...guarda l'ultimo post che c'è il file zippato :
https://forum.lvgl.io/t/esp32-use-with-lvgl-library-need-a-little-example/7295/10
    Ciao
    
    
    Il 19/12/2021 09:11, Renzo Mischianti
      ha scritto:
    
    
      Hi Gabry,
        I know that warning, but don't generate any problems.
        Thanks Renzo
      —
        Reply to this email directly, view
          it on GitHub, or unsubscribe.
        Triage notifications on the go with GitHub Mobile for iOS
        or Android.
        
        You are receiving this because you authored the thread.Message ID: ***@***.***>
      [
{
***@***.***": "http://schema.org",
***@***.***": "EmailMessage",
"potentialAction": {
***@***.***": "ViewAction",
"target": "https://github.com/xreef/SimpleFTPServer/issues/7#issuecomment-997347767",
"url": "https://github.com/xreef/SimpleFTPServer/issues/7#issuecomment-997347767",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
***@***.***": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by xreef** [comment]
Ciao Gabry,
ahh ok la domanda perciò è se modificando FTP_BUF_SIZE cambia la dimensione del buffer.. 
La risposta è si, ma comunque sarà vincolato dalla libreria che effettua la lettura dei file e dalla dimensione del buffer della connessione.
Perciò magari metti 32000 ma non è supportato dai canali e rimane a 1024 che è lo standard in molti casi.
Se attivi il debug dovresti averne visione.

Con le LVGL ho iniziato pure io a fare qualche cosa, ma ora sono sotto con le librerie LoRa ed il cronotermostato è rimasto li senza vita.

Ciao Renzo

**Comment by Gabryxx** [comment]
Mmmm....usi LoRa perchè il termotermostato è molto
      distante?....non l'ho provato ma le recensioni che si leggono in
      giro non sono così entusiasmanti da giustificare
      l'acquisto/aggiunta a un Esp32 col normale wifi e magari
      un'antenna direzionale esterna...qua un test delle antenne 360
      gradi, ma io ne ho una direzionale che aumenta di parecchio i Db:
    https://diyprojects.io/esp32-cam-solder-the-external-antenna-to-improve-the-range-and-stability-of-the-video-stream/#.YcWLtvDMJhE
    ciao e buon divertimento
    
    
    Il 23/12/2021 14:20, Renzo Mischianti
      ha scritto:
    
    
      Ciao Gabry,
        ahh ok la domanda perciò è se modificando FTP_BUF_SIZE cambia la
        dimensione del buffer..
        La risposta è si, ma comunque sarà vincolato dalla libreria che
        effettua la lettura dei file e dalla dimensione del buffer della
        connessione.
        Perciò magari metti 32000 ma non è supportato dai canali e
        rimane a 1024 che è lo standard in molti casi.
        Se attivi il debug dovresti averne visione.
      Con le LVGL ho iniziato pure io a fare qualche cosa,
        ma ora sono sotto con le librerie LoRa ed il cronotermostato è
        rimasto li senza vita.
      Ciao Renzo
      —
        Reply to this email directly, view
          it on GitHub, or unsubscribe.
        Triage notifications on the go with GitHub Mobile for iOS
        or Android.
        
        You are receiving this because you authored the thread.Message ID: ***@***.***>
      [

{

***@***.***": "http://schema.org",

***@***.***": "EmailMessage",

"potentialAction": {

***@***.***": "ViewAction",

"target": "https://github.com/xreef/SimpleFTPServer/issues/7#issuecomment-1000300568",

"url": "https://github.com/xreef/SimpleFTPServer/issues/7#issuecomment-1000300568",

"name": "View Issue"

},

"description": "View this Issue on GitHub",

"publisher": {

***@***.***": "Organization",

"name": "GitHub",

"url": "https://github.com"

}

}

]

**Comment by Gabryxx** [comment]
Per la precisione l'antenna che uso è questa: 
    
    D-Link ANT24-0600 Indoor 2.4GHz 6dBi Gain Antenna
    
    Il 24/12/2021 10:04, gabryxxxxp ha
      scritto:
    
    
      
      Mmmm....usi LoRa perchè il termotermostato è molto
        distante?....non l'ho provato ma le recensioni che si leggono in
        giro non sono così entusiasmanti da giustificare
        l'acquisto/aggiunta a un Esp32 col normale wifi e magari
        un'antenna direzionale esterna...qua un test delle antenne 360
        gradi, ma io ne ho una direzionale che aumenta di parecchio i
        Db:
      https://diyprojects.io/esp32-cam-solder-the-external-antenna-to-improve-the-range-and-stability-of-the-video-stream/#.YcWLtvDMJhE
      ciao e buon divertimento
      
      
      Il 23/12/2021 14:20, Renzo Mischianti
        ha scritto:
      
      
        Ciao Gabry,
          ahh ok la domanda perciò è se modificando FTP_BUF_SIZE cambia
          la dimensione del buffer..
          La risposta è si, ma comunque sarà vincolato dalla libreria
          che effettua la lettura dei file e dalla dimensione del buffer
          della connessione.
          Perciò magari metti 32000 ma non è supportato dai canali e
          rimane a 1024 che è lo standard in molti casi.
          Se attivi il debug dovresti averne visione.
        Con le LVGL ho iniziato pure io a fare qualche
          cosa, ma ora sono sotto con le librerie LoRa ed il
          cronotermostato è rimasto li senza vita.
        Ciao Renzo
        —
          Reply to this email directly, view
            it on GitHub, or unsubscribe.
          Triage notifications on the go with GitHub Mobile for iOS
          or Android.
          
          You are receiving this because you authored the thread.Message ID: ***@***.***>
        [

{

***@***.***": "http://schema.org",

***@***.***": "EmailMessage",

"potentialAction": {

***@***.***": "ViewAction",

"target": "https://github.com/xreef/SimpleFTPServer/issues/7#issuecomment-1000300568",

"url": "https://github.com/xreef/SimpleFTPServer/issues/7#issuecomment-1000300568",

"name": "View Issue"

},

"description": "View this Issue on GitHub",

"publisher": {

***@***.***": "Organization",

"name": "GitHub",

"url": "https://github.com"

}

}

]

**Comment by xreef** [comment]
No no il LoRa è un'altra attività.. 
Io uso i Tenda O3 per controllare i dispositivi a qualche chilometro di distanza.
Ciao Renzo
